In [1]:
import jax
import jax.numpy as jnp

In [23]:
neurons = jnp.array([
    [0, 0, 3, 4, 2], # batch sample 0
    [1, 2, 0, -1, -1], # batch sample 1
    [3, -1, -1, -1, -1] # batch sample 2
])
Nbatch, Nspike = neurons.shape

labels = jnp.array([1, 2, 3]) # one label per batch sample
assert labels.shape == (Nbatch,)

N = 10
Nout = 10

neurons_true = N - Nout + labels[:, jnp.newaxis]
neurons_true

Array([[1],
       [2],
       [3]], dtype=int32)

In [18]:
neurons == neurons_true

Array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False, False]], dtype=bool)

In [19]:
Nspike_out_true_total = jnp.sum(neurons == neurons_true)
activity_out_true = Nspike_out_true_total / Nbatch
activity_out_true

Array(0.6666667, dtype=float32)

In [33]:
out_true_mask = labels[:, jnp.newaxis] == jnp.arange(Nout)
assert out_true_mask.shape == (Nbatch, Nout)
out_true_mask

Array([[False,  True, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False]], dtype=bool)

In [42]:
key = jax.random.PRNGKey(0)
out_vals = jax.random.uniform(key, (Nbatch, Nout))
out_vals

Array([[0.38831604, 0.82557344, 0.15744662, 0.9216856 , 0.8541341 ,
        0.81880295, 0.33484733, 0.83797956, 0.28858185, 0.5061135 ],
       [0.01882851, 0.7104969 , 0.8197037 , 0.71717155, 0.7650944 ,
        0.5481789 , 0.37306917, 0.9477587 , 0.59677327, 0.08364284],
       [0.27055883, 0.5558171 , 0.7998272 , 0.136899  , 0.14062798,
        0.12721694, 0.27647746, 0.43810904, 0.35078037, 0.13254273]],      dtype=float32)

In [43]:
out_vals_true = out_vals[out_true_mask]
out_vals_true

Array([0.82557344, 0.8197037 , 0.136899  ], dtype=float32)

In [54]:
"2024-10-07_10-11-12" > "2024-10-07"

True